### ISSUE TITLE
proxy for couchdb had to be configured manually?

### ISSUE THREAD

**Issue by yaromins** [OpenAgInitiative/openag_brain_install_rpi#2]
To easy up development and testing for myself I decided to switch from setup with docker containers to direct install. 

Looks like install script only installs couchdb, but do not modify default configuration. In my case I had to manually add proxy for openag_brain api. If that is so, maybe it makes sense to include copy of local.ini into this repo and install it into /etc/couchdb during install.

**Comment by LeonChambers** [comment]
The logic for configuring the database is in `openag_python`. In particular, the `openag db init` command should set up the proxy. The command is called in `openag_brain` when you do `rosrun openag_brain main`

**Comment by yaromins** [comment]
Ok, thanks. I'll take a look why it does not work as expected in my case. Maybe it is due my initial attempt to keep db in docker container and move only api to the rpi itself.

**Comment by yaromins** [comment]
Seems it is related to default values. When I just run `rosrun openag_brain main` and try to access to api through couchdb proxy I get an error:

> {
> "error": "error",
> "reason": "{conn_failed,{error,econnrefused}}"
> }

Only when I explicitly set an API url with `rosrun openag_brain main -A http://localhost:5000` I get it working.

I did not look at source code yet, but my guess that either proxy is not setup at all when there is no `-A` is set or default value for API endpoint url is different from the assumed by proxy.

**Comment by yaromins** [comment]
Yep, if there is no -A is given to `main` script, then, in turn, no --api_url param is given to `openag db init` and no default value set in [**init**.py](https://github.com/OpenAgInitiative/openag_python/blob/master/openag/cli/db/__init__.py#L20)

Is there a special reason for this or I can create a PR with adding default value `@click.option("--api_url", default="http://localhost:5000")` ?

**Comment by yaromins** [comment]
I'm closing this issue here and open new one in openag_python repo instead

**Comment by gordonbrander** [comment]
I was surprised by this same issue. Probably a good idea to have a default here.
